### ISSUE TITLE
compile fail with builddeb.sh

### ISSUE THREAD

**Issue by Carpintonto** [Motion-Project/motion-packaging#13]
no errors until the end @ line 479 of bionic_motion_4.3.0+git20200122-346ad0d-buildlog-x86_64.txt

> checking whether the C compiler works... no
> configure: error: in `/tmp/motion.8i6rzY/motion':
> configure: error: C compiler cannot create executables
> See `config.log' for more details

find and locate cannot find or locate  a config.log for this build.
Would that be because line # 471 has a make clean directive?

Ubuntu 18.04.4 LTS

[bionic_motion_4.3.0+git20200122-346ad0d-buildlog-x86_64.txt](https://github.com/Motion-Project/motion/files/4301340/bionic_motion_4.3.0%2Bgit20200122-346ad0d-buildlog-x86_64.txt)

**Comment by Carpintonto** [comment]
I might have a clue here.  I tried editing builddeb.sh at lines 248 and 249 to not remove the $TEMPDIR but just copy it.

`  cp $TEMPDIR/motion_$VERSION* $BASEDIR`
  `# rm -rf $TEMPDIR`

The resulting bionic_motion_4.3.0+git20200122-346ad0d-buildlog-x86_64.txt said
dpkg-checkbuilddeps: error: Unmet build dependencies: libmariadbclient-dev

I installed libmariadbclient-dev which removed 
default-libmysqlclient-dev libgdal-dev libmysqlclient-dev

I then re-edited bionic_motion_4.3.0+git20200122-346ad0d-buildlog-x86_64.txt back to original

` mv $TEMPDIR/motion_$VERSION* $BASEDIR`
  `rm -rf $TEMPDIR`

then re-ran builddeb.sh which failed:

> The following packages need to be installed with the following command: sudo apt-get install  default-libmysqlclient-dev
> john@OptiPlex-780:~/motion_build$ sudo apt-get install  default-libmysqlclient-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  default-libmysqlclient-dev : Depends: libmysqlclient-dev but it is not going to be installed
> E: Unable to correct problems, you have held broken packages

For now I'll reinstall default-libmysqlclient-dev, libgdal-dev, libmysqlclient-dev

Also, the checksums are all good for 
bionic_motion_4.3.0+git20200122-346ad0d-1.debian.tar.xz  
and
bionic_motion_4.3.0+git20200122-346ad0d.orig.tar.gz
before my editing attempt.

Attached is after reinstalling default-libmysqlclient-dev, libgdal-dev, libmysqlclient-dev
builddeb.sh wants mysql dependencies but bionic_motion_4.3.0+git20200307-4eab1d4-buildlog-x86_64.txt reports "Unmet build dependencies: libmariadbclient-dev"; and those packages conflict.
[bionic_motion_4.3.0+git20200307-4eab1d4-buildlog-x86_64.txt](https://github.com/Motion-Project/motion-packaging/files/4303331/bionic_motion_4.3.0%2Bgit20200307-4eab1d4-buildlog-x86_64.txt)

**Comment by Mr-Dave** [comment]
I think the updated script and rules included in the latest commits will resolve "most" of this issue.   Please make sure to get the latest script since the comment above shows use of the old script.

The portion of this issue the commits will not resolve is mysql versus mariadb.  This packaging will now only support the mariadb variant so the package `default-libmysqlclient-dev` is replaced with `libmariadbclient-dev` in the script as well as in the rules file.    

If you want to use mysql instead of mariadb, you will need to edit the `debian/rules` file.

**Comment by Carpintonto** [comment]
I just went with mariadb and the indicated packages from the new version - here's the tail

> dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libwebp.so.7 (used by debian/motion/usr/bin/motion)
> Hint: check if the library actually comes from a package.
> dh_shlibdeps: dpkg-shlibdeps -Tdebian/motion.substvars debian/motion/usr/bin/motion returned exit code 25
> dh_shlibdeps: Aborting due to earlier error
> debian/rules:11: recipe for target 'binary' failed
> make: *** [binary] Error 2
> dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
>

**Comment by Mr-Dave** [comment]
I just tested it on a fresh install of 18.04 as well as my development machine and it worked without issue.  Perhaps validate that on your machine you have the `libwebp-dev` package installed (or reinstall it?)

**Comment by Carpintonto** [comment]
same tail after reinstalling `libwebp-dev`

> ~/motion_build$ file /usr/local/lib/libwebp.so.7
> /usr/local/lib/libwebp.so.7: symbolic link to libwebp.so.7.0.2

> ~/motion_build$ file /usr/local/lib/libwebp.so.7.0.2
> /usr/local/lib/libwebp.so.7.0.2: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1fbc6df697b81390357a3a29dbde462442cb40fc, with debug_info, not stripped
