### ISSUE TITLE
No motion package in Debian Bookworm

### ISSUE THREAD

**Issue by MichaIng** [Motion-Project/motion-packaging#19]
Hey guys, not sure how much you are in contact with the Debian motion package maintainer(s), but there is currently no motion package on Debian Bookworm and the version in unstable/Sid is still ancient 4.3.2, which also affects all Ubuntu versions.

The reason seems to be a bug in 4.3.x with newer FFmpeg, which has long been solved in the meantime, but the block is still present: https://tracker.debian.org/pkg/motion

On the related bug report, the package maintainer is not reacting. The first freeze stage for Bookworm has already been reached, next will be on February 12, which might be the latest date to ship the required motion upstream version update and migrate everything into testing/Bookworm. It would be a pain to not have motion in next Debian release this summer and an ancient version in all Ubuntu versions just because of a communication gap: https://bugs.debian.org/1004629

**Comment by Mr-Dave** [comment]
I do not have any contact with the debian maintainer and do not have any idea on how to proceed.  It looked like there were email addresses originating from debian.org and canonical.com.  Would they know how to get it out of this status?  I'm not a debian maintainer and have zero knowledge of the process/rules.

**Comment by MichaIng** [comment]
Okay, I think best is to directly email the maintainer Ximin Luo as well as the bug reporter Sebastian Ramacher, which is as well form Debian and probably set the block.

Canonical has fixed it, this is the reason they can offer the old motion on recent Ubuntu with recent FFmpeg. However, this won't be patched for Bullseye anymore, I guess, but for Bookworm nothing stands in the way aside of nobody reacting.

I think as Motion-Project maintainer, it would be best if you sent the email, making both aware of the new upstream motion version with full support for FFmpeg 5, as well as the patch provided by Canonical to fix motion 4.3.2 (if needed for some reason), successfully used in Ubuntu Kinetic and Lunar.

**Comment by Mr-Dave** [comment]
Ok.  Email sent.  I'm not optimistic

**Comment by MichaIng** [comment]
At least it was tried, many thanks 🙂. Since you provide DEB packages here as well, if the contact attempt fails, next I'd ask you for Bookworm builds 😛. But requires some adjustment about how the distro version is obtained.

**Comment by Mr-Dave** [comment]
There is a new maintainer and looks like this is resolved.  4.5.1 is in testing/bookworm

**Comment by MichaIng** [comment]
Fantastic news 👍😃.
