### ISSUE TITLE
Wrong missing packages text in builddeb.sh 

### ISSUE THREAD

**Issue by GregDeMare** [Motion-Project/motion-packaging#22]
Wrong missing packages text in builddeb.sh 
if !( dpkg-query -W -f'${Status}' "libcamera-v4l2"   2>/dev/null | grep -q "ok installed"); then MISSINGPKG=$MISSINGPKG" libcamera-dev"; fi

should be if !( dpkg-query -W -f'${Status}' "libcamera-v4l2"   2>/dev/null | grep -q "ok installed"); then MISSINGPKG=$MISSINGPKG" libcamera-v4l2"; fi

**Comment by Mr-Dave** [comment]
Thanks!
